//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MenuPlanner.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditLogs
    {
        public long Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public string ActionType { get; set; }
        public string TableName { get; set; }
        public Nullable<int> RecordId { get; set; }
        public string Details { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
