//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MenuPlanner.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ingredients
    {
        public Ingredients()
        {
            this.InventoryBatches = new HashSet<InventoryBatches>();
            this.PriceHistory = new HashSet<PriceHistory>();
            this.PurchaseRequests = new HashSet<PurchaseRequests>();
            this.RecipeIngredients = new HashSet<RecipeIngredients>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Unit { get; set; }
        public Nullable<int> ShelfLifeDays { get; set; }
        public Nullable<decimal> DefaultPrice { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CategoryId { get; set; }
    
        public virtual Categories Categories { get; set; }
        public virtual ICollection<InventoryBatches> InventoryBatches { get; set; }
        public virtual ICollection<PriceHistory> PriceHistory { get; set; }
        public virtual ICollection<PurchaseRequests> PurchaseRequests { get; set; }
        public virtual ICollection<RecipeIngredients> RecipeIngredients { get; set; }
    }
}
