//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MenuPlanner.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ingredients
    {
        public Ingredients()
        {
            this.Inventory = new HashSet<Inventory>();
            this.PriceHistory = new HashSet<PriceHistory>();
            this.RecipeIngredients = new HashSet<RecipeIngredients>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int CategoryId { get; set; }
        public int UnitId { get; set; }
        public Nullable<int> SupplierId { get; set; }
        public decimal CurrentPrice { get; set; }
        public Nullable<System.DateTime> LastPriceUpdate { get; set; }
        public Nullable<int> ShelfLifeDays { get; set; }
        public string StorageCondition { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedAt { get; set; }
    
        public virtual Categories Categories { get; set; }
        public virtual Suppliers Suppliers { get; set; }
        public virtual Units Units { get; set; }
        public virtual ICollection<Inventory> Inventory { get; set; }
        public virtual ICollection<PriceHistory> PriceHistory { get; set; }
        public virtual ICollection<RecipeIngredients> RecipeIngredients { get; set; }
    }
}
