//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MenuPlanner.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory
    {
        public int Id { get; set; }
        public int IngredientId { get; set; }
        public decimal Quantity { get; set; }
        public string BatchNumber { get; set; }
        public Nullable<System.DateTime> ProductionDate { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public System.DateTime LastCheckDate { get; set; }
    
        public virtual Ingredients Ingredients { get; set; }
    }
}
