//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MenuPlanner.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryBatches
    {
        public int Id { get; set; }
        public Nullable<int> IngredientId { get; set; }
        public string BatchNumber { get; set; }
        public decimal Quantity { get; set; }
        public System.DateTime ReceivedDate { get; set; }
        public System.DateTime ExpirationDate { get; set; }
        public string Status { get; set; }
        public Nullable<int> SupplierId { get; set; }
        public Nullable<decimal> CostPerUnit { get; set; }
    
        public virtual Ingredients Ingredients { get; set; }
        public virtual Suppliers Suppliers { get; set; }
    }
}
