//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MenuPlanner.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuItems
    {
        public int Id { get; set; }
        public Nullable<int> MenuId { get; set; }
        public Nullable<int> RecipeId { get; set; }
        public Nullable<int> PlannedPortions { get; set; }
        public Nullable<int> SortOrder { get; set; }
    
        public virtual Menus Menus { get; set; }
        public virtual Recipes Recipes { get; set; }
    }
}
