//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MenuPlanner.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PriceHistory
    {
        public int Id { get; set; }
        public int IngredientId { get; set; }
        public decimal OldPrice { get; set; }
        public decimal NewPrice { get; set; }
        public System.DateTime ChangedAt { get; set; }
        public Nullable<int> ChangedByUserId { get; set; }
    
        public virtual Ingredients Ingredients { get; set; }
        public virtual Users Users { get; set; }
    }
}
