//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MenuPlanner.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recipes
    {
        public Recipes()
        {
            this.RecipeIngredients = new HashSet<RecipeIngredients>();
            this.SalesStats = new HashSet<SalesStats>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string RecipeNumber { get; set; }
        public int CategoryId { get; set; }
        public int BaseServings { get; set; }
        public decimal YieldWeight { get; set; }
        public string Technology { get; set; }
        public string Presentation { get; set; }
        public decimal MarkupPercent { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> AuthorId { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
    
        public virtual Categories Categories { get; set; }
        public virtual ICollection<RecipeIngredients> RecipeIngredients { get; set; }
        public virtual Users Users { get; set; }
        public virtual ICollection<Sales> Sales { get; set; }
        public virtual Categories Categories { get; set; }
    }
}
