//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MenuPlanner.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recipes
    {
        public Recipes()
        {
            this.MenuItems = new HashSet<MenuItems>();
            this.RecipeIngredients = new HashSet<RecipeIngredients>();
            this.Sales = new HashSet<Sales>();
            this.MarkupPercent = 0;
            this.IsActive = true;
            this.BaseServings = 1;
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        
        // Новые поля из ТЗ
        public string RecipeNumber { get; set; }
        public string Source { get; set; }
        public int BaseServings { get; set; }
        public Nullable<decimal> YieldWeight { get; set; }
        public string Technology { get; set; }
        public Nullable<decimal> MarkupPercent { get; set; }
        public bool IsActive { get; set; }
        
        // Внешний ключ на категорию
        public Nullable<int> CategoryId { get; set; }

        public virtual ICollection<MenuItems> MenuItems { get; set; }
        public virtual ICollection<RecipeIngredients> RecipeIngredients { get; set; }
        public virtual Users Users { get; set; }
        public virtual ICollection<Sales> Sales { get; set; }
        public virtual Categories Categories { get; set; }
    }
}
