//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MenuPlanner.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesStats
    {
        public int Id { get; set; }
        public int RecipeId { get; set; }
        public System.DateTime SaleDate { get; set; }
        public int PortionsSold { get; set; }
        public decimal TotalRevenue { get; set; }
        public decimal CostAtMoment { get; set; }
    
        public virtual Recipes Recipes { get; set; }
    }
}
