//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MenuPlanner.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Suppliers
    {
        public Suppliers()
        {
            this.InventoryBatches = new HashSet<InventoryBatches>();
            this.PriceHistory = new HashSet<PriceHistory>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string ContactPhone { get; set; }
        public string Email { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual ICollection<InventoryBatches> InventoryBatches { get; set; }
        public virtual ICollection<PriceHistory> PriceHistory { get; set; }
    }
}
