//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MenuPlanner.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.AuditLogs = new HashSet<AuditLogs>();
            this.Menus = new HashSet<Menus>();
            this.PurchaseRequests = new HashSet<PurchaseRequests>();
            this.PurchaseRequests1 = new HashSet<PurchaseRequests>();
            this.Recipes = new HashSet<Recipes>();
        }
    
        public int Id { get; set; }
        public string Login { get; set; }
        public string PasswordHash { get; set; }
        public string FullName { get; set; }
        public int RoleId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
    
        public virtual ICollection<AuditLogs> AuditLogs { get; set; }
        public virtual ICollection<Menus> Menus { get; set; }
        public virtual ICollection<PurchaseRequests> PurchaseRequests { get; set; }
        public virtual ICollection<PurchaseRequests> PurchaseRequests1 { get; set; }
        public virtual ICollection<Recipes> Recipes { get; set; }
        public virtual Roles Roles { get; set; }
    }
}
